apt-get dist-upgrade to jessie

diff --git a/var/lib/dpkg/info/systemd.postinst b/var/lib/dpkg/info/systemd.postinst
--- a/var/lib/dpkg/info/systemd.postinst
+++ b/var/lib/dpkg/info/systemd.postinst
@@ -3,23 +3,32 @@
 set -e
 
 _systemctl() {
-    if [ -e /sys/fs/cgroup/systemd ]; then
+    if [ -d /run/systemd/system ]; then
         systemctl "$@"
     fi
 }
 
-if [ "$1" = triggered ]; then
-    /lib/systemd/debian-enable-units
+_update_catalog() {
+    journalctl --update-catalog || true
+}
+
+# Update Message Catalogs database in response to dpkg trigger
+if [ "$1" = "triggered" ]; then
+    _update_catalog
     exit 0
 fi
 
-# Run the script after the initial installation or once on upgrades
-if [ -z "$2" ] || dpkg --compare-versions "$2" lt "44-9"; then
-    /lib/systemd/debian-enable-units
+# Cleanup state files from the auto-enabler which we used in wheezy
+if dpkg --compare-versions "$2" lt "204-1"; then
+    rm -f /var/lib/systemd/enabled-units
+    rm -f /var/lib/systemd/run-debian-enable-units
+    rm -f /var/lib/systemd/*.symlinks
 fi
 
 if [ -n "$2" ]; then
     _systemctl daemon-reexec || true
+    _systemctl try-restart systemd-journald.service || true
+    _systemctl try-restart systemd-logind.service || true
 fi
 
 # Do a one-time migration of the local time setting
@@ -33,7 +42,13 @@ if dpkg --compare-versions "$2" lt "33-1"; then
 fi
 
 # Do a one-time migration of the TMPTIME setting
-if dpkg --compare-versions "$2" lt "36-2"; then
+if dpkg --compare-versions "$2" lt "204-9"; then
+    # Fix up potentially broken tmp.conf, see Debian#738862
+    if [ -e /etc/tmpfiles.d/tmp.conf ]; then
+        sed -i '/^# Clear \/var\/tmp/d' /etc/tmpfiles.d/tmp.conf
+        sed -i 's,^\(d /var/tmp\),#\1,g' /etc/tmpfiles.d/tmp.conf
+    fi
+
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -41,18 +56,28 @@ if dpkg --compare-versions "$2" lt "36-2"; then
         case "$TMPTIME" in
             -*|infinite|infinity)
                 cat > /etc/tmpfiles.d/tmp.conf <<EOF
-# Automatically migrated from TMPTIME in /etc/default/rcS
-# Clear /var/tmp as in /usr/lib/tmpfiles.d/tmp.conf, but avoid clearing /tmp
-d /var/tmp 1777 root root 30d
+# Avoid clearing /tmp by shipping an empty /etc/tmpfiles.d/tmp.conf file
+# which overrides /usr/lib/tmpfiles.d/tmp.conf.
+# This file was automatically created because of local modifications in
+# /etc/default/rcS where TMPTIME was set to infinite.
 EOF
                 ;;
         esac
     fi
 fi
 
-# Create /run/initctl → /dev/initctl compat symlink on upgrades
-if [ -e /sys/fs/cgroup/systemd ]; then
-    _systemctl restart systemd-initctl.socket || true
+# Do a one-time migration of the RAMTMP setting
+if dpkg --compare-versions "$2" lt "204-8"; then
+    if [ -f /etc/default/rcS ]; then
+        . /etc/default/rcS
+    fi
+    if [ -f /etc/default/tmpfs ]; then
+        . /etc/default/tmpfs
+    fi
+    if [ "$RAMTMP" = "yes" ]; then
+        # systemctl enable will work even when systemd is not the active PID 1.
+        systemctl enable tmp.mount || true
+    fi
 fi
 
 if dpkg --compare-versions "$2" lt "40-1"; then
@@ -62,14 +87,29 @@ if dpkg --compare-versions "$2" lt "40-1"; then
     if [ -d /lib/init/rw ]; then
         rmdir --ignore-fail-on-non-empty /lib/init/rw || true
     fi
-
-    # Create /run/initctl → /dev/initctl compat symlink on upgrades
-    if [ -e /sys/fs/cgroup/systemd ]; then
-        ln -sf /dev/initctl /run/initctl
-    fi
 fi
 
 systemd-machine-id-setup
+
+if ! getent group systemd-journal >/dev/null; then
+    addgroup --system systemd-journal
+fi
+
+# initial update of the Message Catalogs database
+_update_catalog
+
+# We don’t ship /var/log/journal currently, so only run the following fix for
+# systems where the administrator has explicitly enabled persistent logging by
+# creating /var/log/journal.
+if [ -d /var/log/journal ]; then
+        # Grant read access to /var/log/journal for members of the adm group
+        # via a filesystem ACL. This makes them able to read the journal.
+        # Failure is ignored since there might be file systems mounted without
+        # ACL support.
+        setfacl -R -nm g:adm:rx,d:g:adm:rx /var/log/journal || true
+fi
+
+setcap cap_dac_override,cap_sys_ptrace=ep /usr/bin/systemd-detect-virt || true
 
 # Automatically added by dh_installdeb
 dpkg-maintscript-helper rm_conffile /etc/lsb-base-logging.sh 25-1~ systemd -- "$@"
@@ -84,6 +124,15 @@ dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/systemd.conf 29-1~ systemd -
 dpkg-maintscript-helper rm_conffile /etc/tmpfiles.d/x11.conf 29-1~ systemd -- "$@"
 # End automatically added section
 # Automatically added by dh_installdeb
-dpkg-maintscript-helper mv_conffile /etc/bash_completion.d/systemctl-bash-completion.sh /etc/bash_completion.d/systemd-bash-completion.sh 44-2~ systemd -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemctl-bash-completion.sh 204-1~ systemd -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/systemd-bash-completion.sh 204-1~ systemd -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-logind.conf /etc/systemd/logind.conf 204-1~ systemd -- "$@"
+# End automatically added section
+# Automatically added by dh_installdeb
+dpkg-maintscript-helper mv_conffile /etc/systemd/systemd-journald.conf /etc/systemd/journald.conf 204-1~ systemd -- "$@"
 # End automatically added section
 
